[package]
name = "backend"
version = "1.0.0"
edition = "2021"

license = "AGPL-3.0"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0"
uuid = { version = "1.11.0", features = [ "v4"] }
chrono = "0.4.39"
jsonwebtoken = "9.3.0"

[dev-dependencies]
regex = "1.11.1"